language: node_js
node_js: node
before_script: npm run build-css
script:
 - npm test
 - npm run lint
deploy:
  provider: firebase
  on:
    branch: develop
  token:
    secure: "GS79zf4LkXMykpAmkHvUM56+qTtrTfTaa1E+2dCBziQHPfaMHJPvP/41Qmz5lzj9aPAxtdi7O1jr8WIQYlbM/gjmZhikz+ph91w1qbf0eMAE4kLK885hvjSb2pu6LAMvg6TZyu4ntjcaumjKle7Hia1EjfU0tfgYuFc+4Q1SM6w2YhIfZF8TyKU4wGGBOLzvchVEMZUsVswMlepcQ8xI5Azj5fymleUVP9CWonIZn2IoJPnrnDt93ndBiY0d7I3Ym+n5rADMi+G/nz6jgQun//Sbh12hMBgspPuSe+3Gfmn0qQyAv85JgkvR8pj23L0sFFdP+I+lC7lHdxkbeerY5X8rYQZKR8QwB1uzPKiwC4nuEJnUPaq3FS7afepmbqk7j138YpdZmq1BMUR9Pm5hzcd6Shg6OyD54c031L5qB12+fVY1f0t5M+u/ORhsAGiOgMaWajiWntf90U3OlYh9jKPJDOMoK2BNdsCUKelzuF3lQzrLAzvQwuEIXCA5colX06r0jXsNG9GrUbnbybv8QxOikc5p3SjbUdqXA8MSmR73T4ucqn3LqXD6XIiguxal62N5NylNFT+oEAeIDBCKIIFpCz4oTT2AS1Cq2ayhQYUwKRJfdLlH8fHai+CepDfrCRf1UsVSWmR5lJvKKsP0Vpu4JEystsTs4iP9caVoP8g="
cache: yarn
